"""create group tables

Revision ID: c12b90cc09dc
Revises: 6290eef544f0
Create Date: 2025-09-17 10:40:44.471552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12b90cc09dc'
down_revision = '6290eef544f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
