"""added new field in expense table

Revision ID: c4625777d195
Revises: 0153e70f43bb
Create Date: 2025-09-17 12:00:03.116657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4625777d195'
down_revision = '0153e70f43bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'amount')
    # ### end Alembic commands ###
